# algorithm
algorithm: score_matching

# training parameters
num_updates: 1000
eval_interval: 10
eval_workers: 10
batch_size: 64
lr: 3e-4

# Diffusion Parameters
num_timesteps: 50
sigma: 3
mode: trajectory
eps: 1e-5
sampler: euler_maruyama # euler_maruyama, predictor_corrector
horizon: 32
max_traj_len: 1000
max_n_traj: 1000

# Model Parameters
embed_dim: 256
dims: [128, 256, 512]