# algorithm
algorithm: score_matching

# training parameters
num_updates: 100000
batch_size: 256
lr: 3e-4

num_timesteps: 100
sigma: 3
mode: trajectory
eps: 1e-5
sampler: euler_maruyama # euler_maruyama, predictor_corrector