defaults: 
  - algorithms: ddpm

seed: 1
# --- Dataset --- 
dataset: hopper-expert-v2
# --- Logging ---
log: False
save_ckpt: False
wandb_project: DiffusionPolicy
wandb_group: debug
wandb_jobtype: Train
